spring:
  datasource:
    url: jdbc:mysql://34.64.47.242:3306/everybook?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 9490
    driver-class-name: com.mysql.cj.jdbc.Driver
#    dbcp2:
#      test-on-borrow: true
#      validation-query: select 1


server:
  port: 9999

mybatis:
  mapper-locations: classpath:/mappers/*.xml